service: budget-tracker-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  environment: ${file(./config/${self:custom.stage}.env.json)}

plugins:
  - serverless-offline

functions:
  rest:
    handler: main.handler
    description: Contain all endpoint for budget tracker  
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true

custom:
  serverless-offline:
    httpPort: 4000
  stage: ${opt:stage, self:provider.stage}